### ISSUE TITLE
Failing tests on NixOS: NotImplementedError: Can't perform this operation for unregistered loader type

### ISSUE THREAD

**Issue by onny** [h4l/rnginline#3]
Hey,
two tests are failing on NixOS, not sure about the error yet: `rnginline/test/test_rnginline.py` and `rnginline/test/test_cmdline.py`. The trace looks like this:
```
rnginline/test/test_rnginline.py:113: in <module>
    test_testcases_testcases = _load_testcases()
rnginline/test/test_rnginline.py:42: in _load_testcases
    assert not [f for _files in [[schema], positive_cases, negative_cases]
rnginline/test/test_rnginline.py:43: in <listcomp>
    for f in _files if not pr.resource_exists(__name__, f)]
/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/pkg_resources/__init__.py:1144: in resource_exists
    return get_provider(package_or_requirement).has_resource(resource_name)
/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/pkg_resources/__init__.py:1415: in has_resource
    return self._has(self._fn(self.module_path, resource_name))
/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/pkg_resources/__init__.py:1482: in _has
    raise NotImplementedError(
E   NotImplementedError: Can't perform this operation for unregistered loader type
```
Best regards
Jonas

**Comment by h4l** [comment]
Cheers Jonas, I'll have a look into it.

**Comment by h4l** [comment]
@onny I've fixed the immediate test failure in #4. However the project is pretty out of date as I've not touched it in many years. I might refresh the general project config/tooling etc separately. It's currently too outdated to make a sensible new release.

If you don't mind me asking, are you a user of rnginline, or looking to package it for NixOS or something else?

**Comment by h4l** [comment]
Ah, I see there's already a nix package for it, which disables these failing tests! 😅 https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/python-modules/rnginline/default.nix#L16

**Comment by onny** [comment]
Thank you, I'll update the package and incldue the patch :)

**Comment by h4l** [comment]
Cool, thanks!
